dist: trusty
sudo: false

branches:
  only:
      #- master

os:
  - linux
    - osx

compiler:
  - gcc
    - clang

language:
  - python

python:
  - 3.4

matrix:
  exclude:
  # On OS X gcc is just a wrapper around clang, so don't waste time testing that
  - os: osx
    compiler: gcc

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ninja; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install meson; fi
    #  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then apt-get install ninja-build; fi
    #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip3 install --upgrade pip setuptools; fi
    #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip3 install .; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip install --user meson; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip -v ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip show ; fi
  - echo $PATH
  - tree
  - ls -R .
  - cd TickCounter
  - meson.py . ../build
  - cd ../build
  - ninja

