dist: trusty
sudo: required

branches:
  only:
      #- master

os:
  - linux
    - osx

compiler:
  - gcc
    - clang

language:
  - cpp

matrix:
  exclude:
  # On OS X gcc is just a wrapper around clang, so don't waste time testing that
  - os: osx
    compiler: gcc

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ninja; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install meson; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then INSTALL=curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ruby -e $INSTALL; fi
    #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then PATH="$HOME/.linuxbrew/bin:$PATH"; fi
  - brew install ninja
  - brew install meson
    #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ninja; fi
    #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install meson; fi
    #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install ninja-build; fi
    #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip3 install meson; fi

script:
  - cd TickCounter
  - meson . ../build
  - cd ../build
  - ninja

