dist: trusty
sudo: required

branches:
  only:
      #- master

os:
  - linux
    - osx

compiler:
  - gcc
    - clang

language:
  - cpp

matrix:
  exclude:
  # On OS X gcc is just a wrapper around clang, so don't waste time testing that
  - os: osx
    compiler: gcc

install: true

before_script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ninja; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install meson; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install ninja-build; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip3 install --user meson; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip3 -v ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip3 show ; fi
  - echo $PATH
  - cd TickCounter
  - meson . ../build
  - cd ../build
  - ninja

