branches:
  only:
      #- master

dist: trusty 
sudo: required

language:
  - cpp
    
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang 

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew install ninja;
        brew install meson;
        elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get -q update -y;
        sudo apt-get -q install ninja-build;
        #sudo apt-get -q install -y python3 python3-dev python3-pip;
        #sudo pip3 install meson;
        fi

before_script:
  - wget https://github.com/mesonbuild/meson/releases/download/0.39.1/meson_0.39.1.tar.gz
  - tar -xvf meson_0.39.1.tar.gz
  - cd meson-0.39.1
  - sudo python3 install_meson.py --prefix=/usr
  - cd ..
  - mkdir build

script:
  - cd TickCounter
  - meson . ../build
  - cd ../build
  - ninja

