dist: trusty
sudo: required

#python:
#  - "3.6"

branches:
  only:
      #- master

os:
  - linux
    #- osx

compiler:
  - gcc
    #- clang

language:
  - cpp

matrix:
  exclude:
  # On OS X gcc is just a wrapper around clang, so don't waste time testing that
  - os: osx
    compiler: gcc

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ninja; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install meson; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install ninja-build; fi
    # - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install python3.6 python3.6-dev -y; fi
    #  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -O https://bootstrap.pypa.io/get-pip.py; fi
    #  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo python3.6 get-pip.py; fi
    #  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo mv /usr/bin/python3 /usr/bin/python3-old; fi
    #  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s /usr/bin/python3.6 /usr/bin/python3; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip3 install meson; fi
    #- mkdir .tmp
    #- curl -L https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip -o .tmp/ninja-linux.zip
    #- unzip .tmp/ninja-linux.zip -d .tmp

    #before_script:
    #- export PATH=$PATH:$PWD/.tmp

script:
  - meson TickCounter build && cd build && ninja

