branches:
  only:
      #- master

sudo: false

os:
  - linux
  - osx

language:
  - cpp

services:
  - docker

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
        brew update
        brew install ninja
        brew install meson
    else
        docker pull jpakkane/mesonci:yakkety
    fi

before_script:
  - mkdir build
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
       meson TickCounter build
       ninja -C build
    else
       echo FROM jpakkane/mesonci:yakkety > Dockerfile
       echo ADD . /root >> Dockerfile
       docker build -t mydock .
       docker run mydock /bin/sh -c "cd /root && TRAVIS=true CC=$CC CXX=$CXX meson TickCounter build && ninja -C build"
    fi

script:
  - echo script

